/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCoachRunRouteImport } from './routes/api/public/coach-run'
import { Route as ApiPublicEvalAgentRouteImport } from './routes/api/public/eval-agent'
import { Route as ApiPublicEvalMatchRouteImport } from './routes/api/public/eval-match'
import { Route as ApiPublicEvalTranslateRouteImport } from './routes/api/public/eval-translate'
import { Route as ApiPublicProcessPendingRouteImport } from './routes/api/public/process-pending'
import { Route as ApiPublicPurgeRouteImport } from './routes/api/public/purge'
import { Route as ApiPublicSmsSimRouteImport } from './routes/api/public/sms-sim'
import { Route as ApiPublicSmsWebhookRouteImport } from './routes/api/public/sms-webhook'
import { Route as ApiPublicVoiceIncomingRouteImport } from './routes/api/public/voice-incoming'
import { Route as ApiPublicVoiceRecordedRouteImport } from './routes/api/public/voice-recorded'
import { Route as ApiPublicVoiceStatusRouteImport } from './routes/api/public/voice-status'
import { Route as ApiPublicWeeklyDigestRouteImport } from './routes/api/public/weekly-digest'
import { Route as ApiPublicWeeklySyncRouteImport } from './routes/api/public/weekly-sync'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoachRunRoute = ApiPublicCoachRunRouteImport.update({
  id: '/api/public/coach-run',
  path: '/api/public/coach-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvalAgentRoute = ApiPublicEvalAgentRouteImport.update({
  id: '/api/public/eval-agent',
  path: '/api/public/eval-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvalMatchRoute = ApiPublicEvalMatchRouteImport.update({
  id: '/api/public/eval-match',
  path: '/api/public/eval-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEvalTranslateRoute = ApiPublicEvalTranslateRouteImport.update({
  id: '/api/public/eval-translate',
  path: '/api/public/eval-translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessPendingRoute = ApiPublicProcessPendingRouteImport.update({
  id: '/api/public/process-pending',
  path: '/api/public/process-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPurgeRoute = ApiPublicPurgeRouteImport.update({
  id: '/api/public/purge',
  path: '/api/public/purge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsSimRoute = ApiPublicSmsSimRouteImport.update({
  id: '/api/public/sms-sim',
  path: '/api/public/sms-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSmsWebhookRoute = ApiPublicSmsWebhookRouteImport.update({
  id: '/api/public/sms-webhook',
  path: '/api/public/sms-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceIncomingRoute = ApiPublicVoiceIncomingRouteImport.update({
  id: '/api/public/voice-incoming',
  path: '/api/public/voice-incoming',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceRecordedRoute = ApiPublicVoiceRecordedRouteImport.update({
  id: '/api/public/voice-recorded',
  path: '/api/public/voice-recorded',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVoiceStatusRoute = ApiPublicVoiceStatusRouteImport.update({
  id: '/api/public/voice-status',
  path: '/api/public/voice-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeeklyDigestRoute = ApiPublicWeeklyDigestRouteImport.update({
  id: '/api/public/weekly-digest',
  path: '/api/public/weekly-digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWeeklySyncRoute = ApiPublicWeeklySyncRouteImport.update({
  id: '/api/public/weekly-sync',
  path: '/api/public/weekly-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp-webhook',
    path: '/api/public/whatsapp-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/coach-run': typeof ApiPublicCoachRunRoute
  '/api/public/eval-agent': typeof ApiPublicEvalAgentRoute
  '/api/public/eval-match': typeof ApiPublicEvalMatchRoute
  '/api/public/eval-translate': typeof ApiPublicEvalTranslateRoute
  '/api/public/process-pending': typeof ApiPublicProcessPendingRoute
  '/api/public/purge': typeof ApiPublicPurgeRoute
  '/api/public/sms-sim': typeof ApiPublicSmsSimRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
  '/api/public/voice-incoming': typeof ApiPublicVoiceIncomingRoute
  '/api/public/voice-recorded': typeof ApiPublicVoiceRecordedRoute
  '/api/public/voice-status': typeof ApiPublicVoiceStatusRoute
  '/api/public/weekly-digest': typeof ApiPublicWeeklyDigestRoute
  '/api/public/weekly-sync': typeof ApiPublicWeeklySyncRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/coach-run': typeof ApiPublicCoachRunRoute
  '/api/public/eval-agent': typeof ApiPublicEvalAgentRoute
  '/api/public/eval-match': typeof ApiPublicEvalMatchRoute
  '/api/public/eval-translate': typeof ApiPublicEvalTranslateRoute
  '/api/public/process-pending': typeof ApiPublicProcessPendingRoute
  '/api/public/purge': typeof ApiPublicPurgeRoute
  '/api/public/sms-sim': typeof ApiPublicSmsSimRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
  '/api/public/voice-incoming': typeof ApiPublicVoiceIncomingRoute
  '/api/public/voice-recorded': typeof ApiPublicVoiceRecordedRoute
  '/api/public/voice-status': typeof ApiPublicVoiceStatusRoute
  '/api/public/weekly-digest': typeof ApiPublicWeeklyDigestRoute
  '/api/public/weekly-sync': typeof ApiPublicWeeklySyncRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/coach-run': typeof ApiPublicCoachRunRoute
  '/api/public/eval-agent': typeof ApiPublicEvalAgentRoute
  '/api/public/eval-match': typeof ApiPublicEvalMatchRoute
  '/api/public/eval-translate': typeof ApiPublicEvalTranslateRoute
  '/api/public/process-pending': typeof ApiPublicProcessPendingRoute
  '/api/public/purge': typeof ApiPublicPurgeRoute
  '/api/public/sms-sim': typeof ApiPublicSmsSimRoute
  '/api/public/sms-webhook': typeof ApiPublicSmsWebhookRoute
  '/api/public/voice-incoming': typeof ApiPublicVoiceIncomingRoute
  '/api/public/voice-recorded': typeof ApiPublicVoiceRecordedRoute
  '/api/public/voice-status': typeof ApiPublicVoiceStatusRoute
  '/api/public/weekly-digest': typeof ApiPublicWeeklyDigestRoute
  '/api/public/weekly-sync': typeof ApiPublicWeeklySyncRoute
  '/api/public/whatsapp-webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/coach-run'
    | '/api/public/eval-agent'
    | '/api/public/eval-match'
    | '/api/public/eval-translate'
    | '/api/public/process-pending'
    | '/api/public/purge'
    | '/api/public/sms-sim'
    | '/api/public/sms-webhook'
    | '/api/public/voice-incoming'
    | '/api/public/voice-recorded'
    | '/api/public/voice-status'
    | '/api/public/weekly-digest'
    | '/api/public/weekly-sync'
    | '/api/public/whatsapp-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/coach-run'
    | '/api/public/eval-agent'
    | '/api/public/eval-match'
    | '/api/public/eval-translate'
    | '/api/public/process-pending'
    | '/api/public/purge'
    | '/api/public/sms-sim'
    | '/api/public/sms-webhook'
    | '/api/public/voice-incoming'
    | '/api/public/voice-recorded'
    | '/api/public/voice-status'
    | '/api/public/weekly-digest'
    | '/api/public/weekly-sync'
    | '/api/public/whatsapp-webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/coach-run'
    | '/api/public/eval-agent'
    | '/api/public/eval-match'
    | '/api/public/eval-translate'
    | '/api/public/process-pending'
    | '/api/public/purge'
    | '/api/public/sms-sim'
    | '/api/public/sms-webhook'
    | '/api/public/voice-incoming'
    | '/api/public/voice-recorded'
    | '/api/public/voice-status'
    | '/api/public/weekly-digest'
    | '/api/public/weekly-sync'
    | '/api/public/whatsapp-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCoachRunRoute: typeof ApiPublicCoachRunRoute
  ApiPublicEvalAgentRoute: typeof ApiPublicEvalAgentRoute
  ApiPublicEvalMatchRoute: typeof ApiPublicEvalMatchRoute
  ApiPublicEvalTranslateRoute: typeof ApiPublicEvalTranslateRoute
  ApiPublicProcessPendingRoute: typeof ApiPublicProcessPendingRoute
  ApiPublicPurgeRoute: typeof ApiPublicPurgeRoute
  ApiPublicSmsSimRoute: typeof ApiPublicSmsSimRoute
  ApiPublicSmsWebhookRoute: typeof ApiPublicSmsWebhookRoute
  ApiPublicVoiceIncomingRoute: typeof ApiPublicVoiceIncomingRoute
  ApiPublicVoiceRecordedRoute: typeof ApiPublicVoiceRecordedRoute
  ApiPublicVoiceStatusRoute: typeof ApiPublicVoiceStatusRoute
  ApiPublicWeeklyDigestRoute: typeof ApiPublicWeeklyDigestRoute
  ApiPublicWeeklySyncRoute: typeof ApiPublicWeeklySyncRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coach-run': {
      id: '/api/public/coach-run'
      path: '/api/public/coach-run'
      fullPath: '/api/public/coach-run'
      preLoaderRoute: typeof ApiPublicCoachRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/eval-agent': {
      id: '/api/public/eval-agent'
      path: '/api/public/eval-agent'
      fullPath: '/api/public/eval-agent'
      preLoaderRoute: typeof ApiPublicEvalAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/eval-match': {
      id: '/api/public/eval-match'
      path: '/api/public/eval-match'
      fullPath: '/api/public/eval-match'
      preLoaderRoute: typeof ApiPublicEvalMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/eval-translate': {
      id: '/api/public/eval-translate'
      path: '/api/public/eval-translate'
      fullPath: '/api/public/eval-translate'
      preLoaderRoute: typeof ApiPublicEvalTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-pending': {
      id: '/api/public/process-pending'
      path: '/api/public/process-pending'
      fullPath: '/api/public/process-pending'
      preLoaderRoute: typeof ApiPublicProcessPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/purge': {
      id: '/api/public/purge'
      path: '/api/public/purge'
      fullPath: '/api/public/purge'
      preLoaderRoute: typeof ApiPublicPurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-sim': {
      id: '/api/public/sms-sim'
      path: '/api/public/sms-sim'
      fullPath: '/api/public/sms-sim'
      preLoaderRoute: typeof ApiPublicSmsSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sms-webhook': {
      id: '/api/public/sms-webhook'
      path: '/api/public/sms-webhook'
      fullPath: '/api/public/sms-webhook'
      preLoaderRoute: typeof ApiPublicSmsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-incoming': {
      id: '/api/public/voice-incoming'
      path: '/api/public/voice-incoming'
      fullPath: '/api/public/voice-incoming'
      preLoaderRoute: typeof ApiPublicVoiceIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-recorded': {
      id: '/api/public/voice-recorded'
      path: '/api/public/voice-recorded'
      fullPath: '/api/public/voice-recorded'
      preLoaderRoute: typeof ApiPublicVoiceRecordedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/voice-status': {
      id: '/api/public/voice-status'
      path: '/api/public/voice-status'
      fullPath: '/api/public/voice-status'
      preLoaderRoute: typeof ApiPublicVoiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-digest': {
      id: '/api/public/weekly-digest'
      path: '/api/public/weekly-digest'
      fullPath: '/api/public/weekly-digest'
      preLoaderRoute: typeof ApiPublicWeeklyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/weekly-sync': {
      id: '/api/public/weekly-sync'
      path: '/api/public/weekly-sync'
      fullPath: '/api/public/weekly-sync'
      preLoaderRoute: typeof ApiPublicWeeklySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-webhook': {
      id: '/api/public/whatsapp-webhook'
      path: '/api/public/whatsapp-webhook'
      fullPath: '/api/public/whatsapp-webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCoachRunRoute: ApiPublicCoachRunRoute,
  ApiPublicEvalAgentRoute: ApiPublicEvalAgentRoute,
  ApiPublicEvalMatchRoute: ApiPublicEvalMatchRoute,
  ApiPublicEvalTranslateRoute: ApiPublicEvalTranslateRoute,
  ApiPublicProcessPendingRoute: ApiPublicProcessPendingRoute,
  ApiPublicPurgeRoute: ApiPublicPurgeRoute,
  ApiPublicSmsSimRoute: ApiPublicSmsSimRoute,
  ApiPublicSmsWebhookRoute: ApiPublicSmsWebhookRoute,
  ApiPublicVoiceIncomingRoute: ApiPublicVoiceIncomingRoute,
  ApiPublicVoiceRecordedRoute: ApiPublicVoiceRecordedRoute,
  ApiPublicVoiceStatusRoute: ApiPublicVoiceStatusRoute,
  ApiPublicWeeklyDigestRoute: ApiPublicWeeklyDigestRoute,
  ApiPublicWeeklySyncRoute: ApiPublicWeeklySyncRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
